option(BUILD_FCV_CORE "Build module core" ON)
option(WITH_FCV_BASE "With submodule base" ON)
option(WITH_FCV_MAT "With submodule mat" ON)
option(WITH_FCV_ALLOCATOR "With submodule allocator" ON)
option(WITH_FCV_BASIC_MATH "With submodule basic_math" ON)
option(WITH_FCV_PARALLEL "With submodule parallel" ON)
option(WITH_FCV_CPU "With submodule cpu" ON)
option(WITH_FCV_OPENCL "With submodule opencl" OFF)
option(WITH_FCV_CMAT "With submodule cmat" ON)

option(BUILD_FCV_IMG_TRANSFORM "Build module img_transform" ON)
option(WITH_FCV_COLOR_CONVERT "With submodule color_convert" ON)
option(WITH_FCV_RESIZE "With submodule resize" ON)
option(WITH_FCV_WARP_AFFINE "With submodule warp_affine" ON)
option(WITH_FCV_WARP_PERSPECTIVE "With submodule warp_perspective" ON)
option(WITH_FCV_ROTATION "With submodule rotation" ON)
option(WITH_FCV_FLIP "With submodule flip" ON)
option(WITH_FCV_SUBTRACT "With submodule subtract" ON)
option(WITH_FCV_COPY_MAKE_BORDER "With submodule copy_make_border" ON)
option(WITH_FCV_CROP "With submodule crop" ON)
option(WITH_FCV_REMAP "With submodule remap" ON)
option(WITH_FCV_ADD_WEIGHTED "With submodule add_weighted" ON)
option(WITH_FCV_EXTRACT_CHANNEL "With submodule extract_channel" ON)

option(BUILD_FCV_IMG_CALCULATION "Build module img_calculation" ON)
option(WITH_FCV_MATRIX_MUL "With submodule matrix_mul" ON)
option(WITH_FCV_NORM "With submodule norm" ON)
option(WITH_FCV_MEAN "With submodule mean" ON)
option(WITH_FCV_MIN_AREA_RECT "With submodule min_area_rect" ON)
option(WITH_FCV_MIN_MAX_LOC "With submodule min_max_loc" ON)
option(WITH_FCV_CONNECTED_COMPONENTS "With submodule connected_components" ON)
option(WITH_FCV_FIND_HOMOGRAPHY "With submodule find_homography" ON)

option(BUILD_FCV_FUSION_API "Build module fusion_api" ON)
option(WITH_FCV_BGR_TO_RGBA_WITH_MASK "With submodule bgr_to_rgba_with_mask" ON)
option(WITH_FCV_NORMALIZE_TO_SUBMEAN_TO_REORDER "With submodule normalize_to_submean_to_reorder" ON)
option(WITH_FCV_SPLIT_TO_MEMCPY "With submodule split_to_memcpy" ON)
option(WITH_FCV_Y420SP_TO_RESIZE_TO_BGR "With submodule y420sp_to_resize_to_bgr" ON)
option(WITH_FCV_BGRA_TO_RESIZE_TO_BGR "With submodule bgra_to_resize_to_bgr" ON)

option(BUILD_FCV_MATH_OPERATOR "Build module math_operator" ON)
option(WITH_FCV_VECTOR_OPERATOR "With submodule vector_operator" ON)

option(BUILD_FCV_MEDIA_IO "Build module media_io" ON)
option(WITH_FCV_IMGCODECS "With submodule imgcodecs" ON)

option(BUILD_FCV_IMG_DRAW "Build module img_draw" ON)
option(WITH_FCV_FILL_POLY "With submodule fill_poly" ON)
option(WITH_FCV_POLY_LINES "With submodule poly_lines" ON)
option(WITH_FCV_CIRCLE "With submodule circle" ON)
option(WITH_FCV_LINE "With submodule line" ON)

